"""Fist

Revision ID: 071f600b1f29
Revises: 
Create Date: 2022-11-20 13:55:50.800223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071f600b1f29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
